# Generated by Django 5.0.6 on 2024-06-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_profile_addresse_alter_profile_auth_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
